{% set name = "bumps" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e1a318e791e2c62fcbe0129ed4b9b5ca952f29e384d4909ddce12a918ca1490
  patches:
    - scripts.patch # use entry points instead of installing scripts

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  entry_points:
    - bumps = bumps.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - six
  run:
    - python >=3.6
    - six
    - numpy
    - scipy

test:
  imports:
    - bumps
    - bumps.dream
    - bumps.gui
    - bumps.mystic
    - bumps.mystic.examples
    - bumps.mystic.optimizer

about:
  home: https://github.com/bumps/bumps
  license: CC-PDDC
  summary: Data fitting with bayesian uncertainty analysis
  doc_url: https://bumps.readthedocs.io/en/latest/
  dev_url: https://github.com/bumps/bumps

extra:
  recipe-maintainers:
    - tschoonj
    - bmaranville
    - mrakitin
