{% set name = "bumps" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4f2ee712a1e468a2ce5c0a32f67739a83331f0cb7b9c50b9e7510daefc12169
  patches:
    - scripts.patch # use entry points instead of installing scripts

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  entry_points:
    - bumps = bumps.cli:main

requirements:
  host:
    - pip
    - python
    - six
  run:
    - python
    - six
    - numpy
    - scipy

test:
  imports:
    - bumps
    - bumps.dream
    - bumps.gui
    - bumps.mystic
    - bumps.mystic.examples
    - bumps.mystic.optimizer
    - bumps.numdifftools

about:
  home: http://www.reflectometry.org/danse/software.html
  license: PUBLIC-DOMAIN
  summary: Data fitting with bayesian uncertainty analysis
  doc_url: https://bumps.readthedocs.io/en/latest/
  dev_url: https://github.com/bumps/bumps

extra:
  recipe-maintainers:
    - tschoonj
