{% set name = "bumps" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3295298f7fe1b2392bb2ff88c7a0ae69d77a7698af580a81570052ca05ba530f
  patches:
    - scripts.patch # use entry points instead of installing scripts

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  entry_points:
    - bumps = bumps.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - bumps
    - bumps.dream
    - bumps.gui
    - bumps.mystic
    - bumps.mystic.examples
    - bumps.mystic.optimizer

about:
  home: https://github.com/bumps/bumps
  license: CC-PDDC
  summary: Data fitting with bayesian uncertainty analysis
  doc_url: https://bumps.readthedocs.io/en/latest/
  dev_url: https://github.com/bumps/bumps

extra:
  recipe-maintainers:
    - tschoonj
    - bmaranville
    - mrakitin
