{% set name = "bumps" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61f9c1035ac20f4e41e17392eb5d6a822e1a6f7c4aa18b35d3c9b0863fc8fac8
  patches:

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  entry_points:
    - bumps = bumps.webview.server.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - h5py
    - dill
    - matplotlib-base
    - blinker
    - aiohttp
    - python-socketio
    - plotly
    - mpld3

test:
  requires:
    - python {{ python_min }}
    - pytest  # testing framework
    - pytest-cov  # coverage reporting
  source_files:
    - pyproject.toml # ensure that the bumps package is included in the test environment
  commands:
    - pytest --pyargs bumps
  imports:
    - bumps
    - bumps.dream
    - bumps.gui
    - bumps.mystic
    - bumps.mystic.examples
    - bumps.mystic.optimizer

about:
  home: https://github.com/bumps/bumps
  license: CC-PDDC
  summary: Data fitting with bayesian uncertainty analysis
  doc_url: https://bumps.readthedocs.io/en/latest/
  dev_url: https://github.com/bumps/bumps

extra:
  recipe-maintainers:
    - tschoonj
    - bmaranville
    - mrakitin
